package com.evansgisgen.geoworld.testing;

import com.evansgisgen.geoworld.GeoWorldMod;
import com.evansgisgen.geoworld.geo.GeoDataset;
import com.evansgisgen.geoworld.geo.GeoTile;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.levelgen.Heightmap;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.server.ServerStartedEvent;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Scripted headless-server scenario, enabled with
 * {@code -Dgeoworld.serverScenario=terrain_survey}.
 *
 * <p>After the server finishes starting (spawn chunks generated by the real
 * {@code GeoChunkGenerator}), force-generates a fixed set of sample columns,
 * dumps per-column evidence ({@code GEOWORLD-SURVEY} lines), evaluates
 * assertions ({@code GEOWORLD-ASSERT}), emits {@code GEOWORLD-RESULT}, and
 * halts the server. {@code scripts/Test-Terrain.ps1} orchestrates the run and
 * parses the markers out of the captured log.
 */
public final class TerrainSurveyScenario {
    private static final Logger LOGGER = LoggerFactory.getLogger(TerrainSurveyScenario.class);
    private static final String PROPERTY = "geoworld.serverScenario";
    private static final int WARMUP_TICKS = 60;

    /**
     * Sample columns: downtown, the Big Blue valley southeast of the anchor,
     * west/north interior, the influence ramp, and vanilla outside coverage.
     */
    private static final int[][] SAMPLES = {
            {0, 0}, {64, 64}, {-128, 96}, {200, -100},
            {1500, 1500}, {1900, 1900}, {2100, 2100},
            {-1500, 0}, {0, -2000},
            // Transect across the eastern boundary ramp (influence 1 -> 0
            // over the outer ~500 m of coverage) — the Phase 4 check that the
            // geographic-to-vanilla blend actually follows the field.
            {3300, -600}, {3500, 0}, {3600, 0}, {3700, 0}, {3800, 0}, {3900, 0},
            // Big Blue River channel (Phase 5): compiled water_depth > 0.
            {1243, 1782}, {-638, 501}, {2100, 824},
            // Road-deck crossings (Phase 6 fix): road class > 0 AND
            // water_depth > 0 — the road must deck over the waterline.
            {57, 1279}, {426, -2658},
            // Roads (Phase 6): US-77 marking/asphalt downtown, sidewalk/curb,
            // and an unpaved track.
            {20, 0}, {13, 0}, {130, 0}, {132, 0}, {923, 1078},
            // Land use (Phase 7): farmland, woods, rail corridor.
            {6, 3522}, {660, 1179}, {0, 1638},
            // Buildings (Phase 8): civic, commercial, residential downtown.
            {62, 0}, {6, 143}, {114, 0},
            // Landmark (Phase 9): the demo house at (200, 60) — sample a
            // roof column so its chunks generate.
            {200, 64},
            // Corridor towns + Lincoln (Phase 10/11): Princeton ~34 km and
            // downtown Lincoln ~60 km north of the Beatrice anchor.
            {2716, -34307}, {2196, -60655}, {2474, -60052},
            {5000, 0}, {-5000, -5000},
    };

    private int warmup = -1;
    private boolean finished;

    public static boolean enabled() {
        return "terrain_survey".equals(System.getProperty(PROPERTY, ""));
    }

    public void register() {
        NeoForge.EVENT_BUS.addListener((ServerStartedEvent e) -> warmup = WARMUP_TICKS);
        NeoForge.EVENT_BUS.addListener((ServerTickEvent.Post e) -> onTick(e.getServer()));
    }

    private void onTick(MinecraftServer server) {
        if (finished || warmup < 0) {
            return;
        }
        if (--warmup == 0) {
            finished = true;
            try {
                run(server);
            } catch (Throwable t) {
                LOGGER.error("GEOWORLD-RESULT ERROR: {}", t.toString(), t);
            } finally {
                server.halt(false);
            }
        }
    }

    private record ColumnReport(int x, int z, int topY, int groundY, int oceanY,
                                int terrainY, BlockState terrainBlock,
                                BlockState top, int waterInTop24, int target,
                                double weight, int waterDepth, int roadClass,
                                int surfaceClass, int buildingClass,
                                int buildingLevels, String biome, boolean landmark,
                                int vanilla, int expected, List<String> topBlocks,
                                boolean sealedOverburden, int validStarts) {}

    private void run(MinecraftServer server) {
        ServerLevel level = server.overworld();
        GeoDataset dataset = GeoWorldMod.dataset();
        LOGGER.info("GEOWORLD-SURVEY-BEGIN dataset='{}' empty={}", dataset.name(), dataset.isEmpty());

        // Introspect the active generator chain so codec/delegate wiring bugs
        // are visible in the artifact log.
        net.minecraft.world.level.chunk.ChunkGenerator gen = level.getChunkSource().getGenerator();
        LOGGER.info("GEOWORLD-GEN class={}", gen.getClass().getName());
        if (gen instanceof com.evansgisgen.geoworld.worldgen.GeoChunkGenerator geo) {
            net.minecraft.world.level.chunk.ChunkGenerator d = geo.delegate();
            LOGGER.info("GEOWORLD-GEN delegate={} seaLevel={} minY={} genDepth={}",
                    d.getClass().getName(), d.getSeaLevel(), d.getMinY(), d.getGenDepth());
            net.minecraft.world.level.NoiseColumn nc = d.getBaseColumn(5000, 0, level,
                    level.getChunkSource().randomState());
            java.util.List<String> col = new java.util.ArrayList<>();
            for (int y = d.getMinY() + d.getGenDepth() - 1; y > d.getMinY() && col.size() < 10; y--) {
                net.minecraft.world.level.block.state.BlockState s = nc.getBlock(y);
                if (!s.isAir()) col.add(y + "=" + s.getBlock());
            }
            LOGGER.info("GEOWORLD-GEN delegateBaseColumn(5000,0) topNonAir={}", col);
        }

        // Vanilla baseline for blend assertions: only meaningful when our
        // generator is active (control runs use the vanilla generator, which
        // ignores the dataset entirely).
        net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator delegate =
                gen instanceof com.evansgisgen.geoworld.worldgen.GeoChunkGenerator geo
                        ? geo.delegate() : null;
        net.minecraft.world.level.levelgen.RandomState randomState =
                level.getChunkSource().randomState();

        com.evansgisgen.geoworld.landmark.LandmarkIndex landmarkIndex =
                gen instanceof com.evansgisgen.geoworld.worldgen.GeoChunkGenerator geo
                        ? geo.landmarks(level.registryAccess())
                        : com.evansgisgen.geoworld.landmark.LandmarkIndex.EMPTY;

        List<ColumnReport> reports = new ArrayList<>();
        for (int[] p : SAMPLES) {
            reports.add(survey(level, dataset, delegate, randomState,
                    landmarkIndex, p[0], p[1]));
        }
        LOGGER.info("GEOWORLD-SURVEY-END");

        boolean pass = true;
        pass &= check("dataset_loaded", !dataset.isEmpty());
        pass &= check("all_columns_generated", reports.stream().allMatch(r -> r.topY > level.getMinBuildHeight()));

        List<ColumnReport> fullInfluence = reports.stream()
                .filter(r -> r.weight >= 0.98 && r.target != GeoTile.NO_DATA)
                .toList();
        pass &= check("full_influence_samples_present", !fullInfluence.isEmpty());
        for (ColumnReport r : fullInfluence) {
            // Terrain surface (vegetation-stripped) is the measure; topY can
            // carry trees from a neighboring chunk's decoration, which is
            // timing-dependent to observe. On wet columns the heightmaps
            // count the water column, so measure the bed with OCEAN_FLOOR.
            // Building shells legitimately rise above terrain — covered by
            // building_shell_* instead. Landmark columns place templates —
            // covered by landmark_demo_house.
            if (r.buildingClass > 0 || r.landmark) {
                continue;
            }
            int measured = r.waterDepth > 0 ? r.oceanY : r.terrainY;
            pass &= check(String.format("height_matches_dataset_%d_%d", r.x, r.z),
                    Math.abs(measured - r.target) <= 6);
        }
        for (ColumnReport r : reports) {
            // Only deformed columns have surface water stripped — untouched
            // vanilla (w == 0) legitimately keeps its oceans and lakes.
            // Compiled water columns are asserted by water_surface_* below.
            if (r.waterDepth > 0 || r.weight <= 0 || delegate == null) {
                continue;
            }
            pass &= check(String.format("no_water_surface_%d_%d", r.x, r.z),
                    !r.top.is(Blocks.WATER));
        }
        // Phase 4: the generated ground must follow lerp(vanilla, geo, w).
        // Measured on the leaf-stripped motion-blocking surface; the slack
        // covers trunks, surface-rule blocks and snow sitting above it.
        // Wet columns are covered by water_surface_* instead (the
        // motion-blocking heightmap reports the water top, not the bed).
        for (ColumnReport r : reports) {
            if (r.expected != GeoTile.NO_DATA && r.waterDepth == 0
                    && r.buildingClass == 0 && !r.landmark) {
                pass &= check(String.format("blend_matches_field_%d_%d", r.x, r.z),
                        Math.abs(r.terrainY - r.expected) <= 12);
            }
        }
        // Phase 5: compiled water columns must actually hold water, with the
        // surface at bed + depth (<= 1 block of rounding slack).
        for (ColumnReport r : reports) {
            if (r.waterDepth > 0 && r.weight >= 0.98 && delegate != null
                    && r.roadClass == 0) {
                pass &= check(String.format("water_surface_%d_%d", r.x, r.z),
                        (r.top.is(Blocks.WATER) || r.top.is(Blocks.ICE))
                                && Math.abs(r.topY - (r.target + r.waterDepth)) <= 1);
            }
        }
        // Road-deck crossings: a wet road column must carry the class's
        // block one block above the waterline, with water kept below it.
        for (ColumnReport r : reports) {
            if (r.waterDepth > 0 && r.roadClass > 0 && r.weight >= 0.98
                    && delegate != null) {
                BlockState roadBlock =
                        com.evansgisgen.geoworld.worldgen.GeoChunkGenerator
                                .roadBlock(r.roadClass);
                boolean deckAtWaterline =
                        Math.abs(r.topY - (r.target + r.waterDepth + 1)) <= 1;
                pass &= check(String.format("road_deck_%d_%d", r.x, r.z),
                        r.top == roadBlock && deckAtWaterline
                                && r.waterInTop24 > 0);
            }
        }
        // Phase 6: compiled road columns render the class's surface block
        // (asphalt, curb, sidewalk, ...).
        for (ColumnReport r : reports) {
            if (r.roadClass > 0 && r.weight >= 0.98 && delegate != null) {
                pass &= check(String.format("road_surface_%d_%d", r.x, r.z),
                        r.top == com.evansgisgen.geoworld.worldgen.GeoChunkGenerator
                                .roadBlock(r.roadClass));
            }
        }
        // Phase 7: classified land-use columns render the class's theme
        // block at the terrain surface (roads/buildings/water own their
        // cells, so they're skipped).
        for (ColumnReport r : reports) {
            if (r.surfaceClass > 0 && r.weight >= 0.98 && delegate != null
                    && r.waterDepth == 0 && r.roadClass == 0
                    && r.buildingClass == 0 && !r.landmark) {
                BlockState expectedBlock =
                        com.evansgisgen.geoworld.worldgen.GeoChunkGenerator
                                .surfaceBlock(r.surfaceClass);
                // A planted tree's trunk column legitimately converts the
                // surface block under it to dirt — accept that on the exact
                // column the trunk stands on.
                boolean trunkBase = r.terrainBlock.is(Blocks.DIRT)
                        && level.getBlockState(new BlockPos(r.x, r.terrainY + 1, r.z))
                                .is(net.minecraft.tags.BlockTags.LOGS);
                pass &= check(String.format("surface_class_%d_%d", r.x, r.z),
                        expectedBlock != null
                                && (r.terrainBlock == expectedBlock || trunkBase));
            }
        }
        // Phase 7: full-coverage columns live in the fixed plains biome —
        // no jungle/frozen-river surprises.
        for (ColumnReport r : reports) {
            if (r.weight >= 0.98 && delegate != null) {
                pass &= check(String.format("biome_plains_%d_%d", r.x, r.z),
                        "minecraft:plains".equals(r.biome));
            }
        }
        // Phase 8: building cells raise a shell — the top sits at least a
        // storey above terrain and is a palette block (roof/wall/window).
        for (ColumnReport r : reports) {
            if (r.buildingClass > 0 && r.weight >= 0.98 && delegate != null
                    && r.waterDepth == 0 && r.roadClass == 0 && !r.landmark) {
                var palette = com.evansgisgen.geoworld.worldgen.GeoChunkGenerator
                        .buildingPalette(r.buildingClass);
                pass &= check(String.format("building_shell_%d_%d", r.x, r.z),
                        palette != null && r.topY >= r.target + 4
                                && (r.top == palette.roof() || r.top == palette.wall()
                                        || r.top == palette.window()));
            }
        }
        // Overburden seal: full-coverage non-building columns must be solid
        // for the 16 m under the deformed surface (bed, on wet columns) —
        // caves still exist deeper, they just can't breach roads/ground.
        // Building shells have interior air; landmarks own their columns.
        for (ColumnReport r : reports) {
            if (r.weight >= 0.98 && delegate != null
                    && r.buildingClass == 0 && !r.landmark) {
                pass &= check(String.format("no_cave_breach_%d_%d", r.x, r.z),
                        r.sealedOverburden);
            }
        }
        // Vanilla structures never start inside claimed ground — villages,
        // shipwrecks, etc. are invalidated when their bbox touches it.
        for (ColumnReport r : reports) {
            if (r.weight >= 0.98 && delegate != null) {
                pass &= check(String.format("no_structures_%d_%d", r.x, r.z),
                        r.validStarts == 0);
            }
        }
        // Phase 9: the demo landmark placed at (200, 60) — anchor [5,0,0]
        // puts the north-face doorway at world (200, ground+1..2, 60) and
        // brick walls either side of it. LEVEL_FOUNDATION flattened the lot.
        {
            GeoTile t = dataset.tileAt(200, 60).orElse(null);
            if (t != null && t.hasElevation()) {
                int g = t.elevation(dataset.localCoord(200), dataset.localCoord(60));
                level.getChunk(200 >> 4, 64 >> 4);
                BlockPos.MutableBlockPos pos = new BlockPos.MutableBlockPos();
                boolean wall = level.getBlockState(pos.set(197, g + 2, 60))
                        .is(Blocks.BRICKS);
                boolean door = level.getBlockState(pos.set(200, g + 2, 60)).isAir()
                        && level.getBlockState(pos.set(200, g + 3, 60)).isAir();
                boolean roof = level.getBlockState(pos.set(200, g + 5, 64))
                        .is(Blocks.DARK_OAK_PLANKS);
                pass &= check("landmark_demo_house", wall && door && roof);
            }
        }
        LOGGER.info("GEOWORLD-RESULT {}", pass ? "PASS" : "FAIL");
    }

    private static boolean check(String name, boolean ok) {
        LOGGER.info("GEOWORLD-ASSERT {} {}", name, ok ? "PASS" : "FAIL");
        return ok;
    }

    private ColumnReport survey(ServerLevel level, GeoDataset dataset,
            @Nullable net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator delegate,
            net.minecraft.world.level.levelgen.RandomState randomState,
            com.evansgisgen.geoworld.landmark.LandmarkIndex landmarkIndex,
            int x, int z) {
        // Force the 3x3 chunk neighborhood to FULL before measuring: feature
        // writes from a neighbor's decoration (e.g. tree leaf overhang) land
        // asynchronously, so sampling without this races chunk population.
        int cx = x >> 4;
        int cz = z >> 4;
        for (int dx = -1; dx <= 1; dx++) {
            for (int dz = -1; dz <= 1; dz++) {
                level.getChunk(cx + dx, cz + dz);
            }
        }
        ChunkAccess chunk = level.getChunk(cx, cz);
        int minY = level.getMinBuildHeight();
        int topY;
        int groundY;
        int oceanY;
        BlockState top;
        int waterInTop24 = 0;
        List<String> topBlocks = new ArrayList<>();
        int terrainY = minY;
        BlockState terrainBlock = Blocks.AIR.defaultBlockState();
        String biome = "?";
        if (chunk == null) {
            topY = minY;
            groundY = minY;
            oceanY = minY;
            top = Blocks.AIR.defaultBlockState();
        } else {
            topY = level.getHeight(Heightmap.Types.WORLD_SURFACE, x, z) - 1;
            groundY = level.getHeight(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, x, z) - 1;
            oceanY = level.getHeight(Heightmap.Types.OCEAN_FLOOR, x, z) - 1;
            BlockPos.MutableBlockPos pos = new BlockPos.MutableBlockPos();
            top = level.getBlockState(pos.set(x, topY, z));
            for (int y = topY; y > topY - 24 && y > minY; y--) {
                BlockState s = level.getBlockState(pos.set(x, y, z));
                if (s.is(Blocks.WATER)) {
                    waterInTop24++;
                }
                if (!s.isAir() && topBlocks.size() < 8) {
                    topBlocks.add(y + "=" + s.getBlock().toString());
                }
            }
            // Terrain surface: same vegetation-skip as the generator's
            // groundHeight — trees/plants above ground don't inflate it.
            for (int y = topY; y > minY; y--) {
                BlockState s = level.getBlockState(pos.set(x, y, z));
                if (!s.isAir() && s.getFluidState().isEmpty()
                        && !com.evansgisgen.geoworld.worldgen.GeoChunkGenerator
                                .isFeatureOverhang(s)) {
                    terrainY = y;
                    terrainBlock = s;
                    break;
                }
            }
            biome = level.getBiome(pos.set(x, groundY, z)).unwrapKey()
                    .map(k -> k.location().toString()).orElse("?");
        }

        int target = GeoTile.NO_DATA;
        double weight = 0.0;
        int waterDepth = 0;
        int roadClass = 0;
        int surfaceClass = 0;
        int buildingClass = 0;
        int buildingLevels = 0;
        GeoTile tile = dataset.tileAt(x, z).orElse(null);
        if (tile != null && tile.hasElevation()) {
            int lx = dataset.localCoord(x);
            int lz = dataset.localCoord(z);
            target = tile.elevation(lx, lz);
            if (tile.hasInfluence()) {
                weight = tile.influenceWeight(lx, lz) / 255.0;
            }
            waterDepth = tile.waterDepth(lx, lz);
            roadClass = tile.roadClass(lx, lz);
            surfaceClass = tile.surfaceClass(lx, lz);
            buildingClass = tile.buildingClass(lx, lz);
            buildingLevels = tile.buildingLevels(lx, lz);
        }

        int vanilla = GeoTile.NO_DATA;
        int expected = GeoTile.NO_DATA;
        if (delegate != null) {
            vanilla = delegate.getBaseHeight(x, z, Heightmap.Types.OCEAN_FLOOR, level, randomState);
            if (target != GeoTile.NO_DATA && weight > 0.0) {
                expected = (int) Math.round(vanilla + (target - vanilla) * weight);
            }
        }

        // Overburden probe: the 16 m below the deformed surface (below the
        // bed on wet columns) must be solid — deformChunk seals cave/aquifer
        // pockets there while leaving deeper caves alone.
        boolean sealedOverburden = true;
        if (chunk != null) {
            int bandTop = waterDepth > 0 ? target : terrainY;
            BlockPos.MutableBlockPos pos = new BlockPos.MutableBlockPos();
            for (int y = bandTop - 1; y >= bandTop - 16 && y > minY; y--) {
                BlockState s = level.getBlockState(pos.set(x, y, z));
                if (s.isAir() || !s.getFluidState().isEmpty()) {
                    sealedOverburden = false;
                    break;
                }
            }
        }
        // Vanilla structure starts living in this chunk — claimed ground
        // must have none (suppressed at createStructures).
        int validStarts = 0;
        if (chunk != null) {
            for (var start : chunk.getAllStarts().values()) {
                if (start.isValid()) {
                    validStarts++;
                }
            }
        }

        LOGGER.info("GEOWORLD-SURVEY x={} z={} topY={} ground={} ocean={} terrain={} top={} waterInTop24={} target={} w={} wd={} road={} surf={} bldg={}/{} biome={} vanilla={} expected={} sealed={} starts={} blocks={}",
                x, z, topY, groundY, oceanY, terrainY, top.getBlock(), waterInTop24, target,
                String.format("%.2f", weight), waterDepth, roadClass, surfaceClass,
                buildingClass, buildingLevels, biome, vanilla, expected,
                sealedOverburden, validStarts, topBlocks);
        return new ColumnReport(x, z, topY, groundY, oceanY, terrainY, terrainBlock,
                top, waterInTop24, target, weight, waterDepth, roadClass,
                surfaceClass, buildingClass, buildingLevels, biome,
                landmarkIndex.contains(x, z), vanilla, expected, topBlocks,
                sealedOverburden, validStarts);
    }
}
