package com.evansgisgen.geoworld.testing;

import com.evansgisgen.geoworld.GeoWorldMod;
import com.evansgisgen.geoworld.geo.GeoDataset;
import com.evansgisgen.geoworld.geo.GeoTile;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.levelgen.Heightmap;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.server.ServerStartedEvent;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Scripted headless-server scenario, enabled with
 * {@code -Dgeoworld.serverScenario=terrain_survey}.
 *
 * <p>After the server finishes starting (spawn chunks generated by the real
 * {@code GeoChunkGenerator}), force-generates a fixed set of sample columns,
 * dumps per-column evidence ({@code GEOWORLD-SURVEY} lines), evaluates
 * assertions ({@code GEOWORLD-ASSERT}), emits {@code GEOWORLD-RESULT}, and
 * halts the server. {@code scripts/Test-Terrain.ps1} orchestrates the run and
 * parses the markers out of the captured log.
 */
public final class TerrainSurveyScenario {
    private static final Logger LOGGER = LoggerFactory.getLogger(TerrainSurveyScenario.class);
    private static final String PROPERTY = "geoworld.serverScenario";
    private static final int WARMUP_TICKS = 60;

    /**
     * Sample columns: downtown, the Big Blue valley southeast of the anchor,
     * west/north interior, the influence ramp, and vanilla outside coverage.
     */
    private static final int[][] SAMPLES = {
            {0, 0}, {64, 64}, {-128, 96}, {200, -100},
            {1500, 1500}, {1900, 1900}, {2100, 2100},
            {-1500, 0}, {0, -2000},
            // Transect across the eastern boundary ramp (influence 1 -> 0
            // over the outer ~500 m of coverage) — the Phase 4 check that the
            // geographic-to-vanilla blend actually follows the field.
            {3300, 0}, {3500, 0}, {3600, 0}, {3700, 0}, {3800, 0}, {3900, 0},
            {5000, 0}, {-5000, -5000},
    };

    private int warmup = -1;
    private boolean finished;

    public static boolean enabled() {
        return "terrain_survey".equals(System.getProperty(PROPERTY, ""));
    }

    public void register() {
        NeoForge.EVENT_BUS.addListener((ServerStartedEvent e) -> warmup = WARMUP_TICKS);
        NeoForge.EVENT_BUS.addListener((ServerTickEvent.Post e) -> onTick(e.getServer()));
    }

    private void onTick(MinecraftServer server) {
        if (finished || warmup < 0) {
            return;
        }
        if (--warmup == 0) {
            finished = true;
            try {
                run(server);
            } catch (Throwable t) {
                LOGGER.error("GEOWORLD-RESULT ERROR: {}", t.toString(), t);
            } finally {
                server.halt(false);
            }
        }
    }

    private record ColumnReport(int x, int z, int topY, int groundY, BlockState top,
                                int waterInTop24, int target, double weight,
                                int vanilla, int expected, List<String> topBlocks) {}

    private void run(MinecraftServer server) {
        ServerLevel level = server.overworld();
        GeoDataset dataset = GeoWorldMod.dataset();
        LOGGER.info("GEOWORLD-SURVEY-BEGIN dataset='{}' empty={}", dataset.name(), dataset.isEmpty());

        // Introspect the active generator chain so codec/delegate wiring bugs
        // are visible in the artifact log.
        net.minecraft.world.level.chunk.ChunkGenerator gen = level.getChunkSource().getGenerator();
        LOGGER.info("GEOWORLD-GEN class={}", gen.getClass().getName());
        if (gen instanceof com.evansgisgen.geoworld.worldgen.GeoChunkGenerator geo) {
            net.minecraft.world.level.chunk.ChunkGenerator d = geo.delegate();
            LOGGER.info("GEOWORLD-GEN delegate={} seaLevel={} minY={} genDepth={}",
                    d.getClass().getName(), d.getSeaLevel(), d.getMinY(), d.getGenDepth());
            net.minecraft.world.level.NoiseColumn nc = d.getBaseColumn(5000, 0, level,
                    level.getChunkSource().randomState());
            java.util.List<String> col = new java.util.ArrayList<>();
            for (int y = d.getMinY() + d.getGenDepth() - 1; y > d.getMinY() && col.size() < 10; y--) {
                net.minecraft.world.level.block.state.BlockState s = nc.getBlock(y);
                if (!s.isAir()) col.add(y + "=" + s.getBlock());
            }
            LOGGER.info("GEOWORLD-GEN delegateBaseColumn(5000,0) topNonAir={}", col);
        }

        // Vanilla baseline for blend assertions: only meaningful when our
        // generator is active (control runs use the vanilla generator, which
        // ignores the dataset entirely).
        net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator delegate =
                gen instanceof com.evansgisgen.geoworld.worldgen.GeoChunkGenerator geo
                        ? geo.delegate() : null;
        net.minecraft.world.level.levelgen.RandomState randomState =
                level.getChunkSource().randomState();

        List<ColumnReport> reports = new ArrayList<>();
        for (int[] p : SAMPLES) {
            reports.add(survey(level, dataset, delegate, randomState, p[0], p[1]));
        }
        LOGGER.info("GEOWORLD-SURVEY-END");

        boolean pass = true;
        pass &= check("dataset_loaded", !dataset.isEmpty());
        pass &= check("all_columns_generated", reports.stream().allMatch(r -> r.topY > level.getMinBuildHeight()));

        List<ColumnReport> fullInfluence = reports.stream()
                .filter(r -> r.weight >= 0.98 && r.target != GeoTile.NO_DATA)
                .toList();
        pass &= check("full_influence_samples_present", !fullInfluence.isEmpty());
        for (ColumnReport r : fullInfluence) {
            // Ground (leaf-stripped motion-blocking top) is the terrain
            // surface; topY can carry trees from a neighboring chunk's
            // decoration, which is timing-dependent to observe.
            pass &= check(String.format("height_matches_dataset_%d_%d", r.x, r.z),
                    Math.abs(r.groundY - r.target) <= 6);
        }
        for (ColumnReport r : reports) {
            pass &= check(String.format("no_water_surface_%d_%d", r.x, r.z),
                    !r.top.is(Blocks.WATER));
        }
        // Phase 4: the generated ground must follow lerp(vanilla, geo, w).
        // Measured on the leaf-stripped motion-blocking surface; the slack
        // covers trunks, surface-rule blocks and snow sitting above it.
        for (ColumnReport r : reports) {
            if (r.expected != GeoTile.NO_DATA) {
                pass &= check(String.format("blend_matches_field_%d_%d", r.x, r.z),
                        Math.abs(r.groundY - r.expected) <= 12);
            }
        }
        LOGGER.info("GEOWORLD-RESULT {}", pass ? "PASS" : "FAIL");
    }

    private static boolean check(String name, boolean ok) {
        LOGGER.info("GEOWORLD-ASSERT {} {}", name, ok ? "PASS" : "FAIL");
        return ok;
    }

    private ColumnReport survey(ServerLevel level, GeoDataset dataset,
            @Nullable net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator delegate,
            net.minecraft.world.level.levelgen.RandomState randomState, int x, int z) {
        // Force the 3x3 chunk neighborhood to FULL before measuring: feature
        // writes from a neighbor's decoration (e.g. tree leaf overhang) land
        // asynchronously, so sampling without this races chunk population.
        int cx = x >> 4;
        int cz = z >> 4;
        for (int dx = -1; dx <= 1; dx++) {
            for (int dz = -1; dz <= 1; dz++) {
                level.getChunk(cx + dx, cz + dz);
            }
        }
        ChunkAccess chunk = level.getChunk(cx, cz);
        int minY = level.getMinBuildHeight();
        int topY;
        int groundY;
        BlockState top;
        int waterInTop24 = 0;
        List<String> topBlocks = new ArrayList<>();
        if (chunk == null) {
            topY = minY;
            groundY = minY;
            top = Blocks.AIR.defaultBlockState();
        } else {
            topY = level.getHeight(Heightmap.Types.WORLD_SURFACE, x, z) - 1;
            groundY = level.getHeight(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, x, z) - 1;
            BlockPos.MutableBlockPos pos = new BlockPos.MutableBlockPos();
            top = level.getBlockState(pos.set(x, topY, z));
            for (int y = topY; y > topY - 24 && y > minY; y--) {
                BlockState s = level.getBlockState(pos.set(x, y, z));
                if (s.is(Blocks.WATER)) {
                    waterInTop24++;
                }
                if (!s.isAir() && topBlocks.size() < 8) {
                    topBlocks.add(y + "=" + s.getBlock().toString());
                }
            }
        }

        int target = GeoTile.NO_DATA;
        double weight = 0.0;
        GeoTile tile = dataset.tileAt(x, z).orElse(null);
        if (tile != null && tile.hasElevation()) {
            int lx = dataset.localCoord(x);
            int lz = dataset.localCoord(z);
            target = tile.elevation(lx, lz);
            if (tile.hasInfluence()) {
                weight = tile.influenceWeight(lx, lz) / 255.0;
            }
        }

        int vanilla = GeoTile.NO_DATA;
        int expected = GeoTile.NO_DATA;
        if (delegate != null) {
            vanilla = delegate.getBaseHeight(x, z, Heightmap.Types.OCEAN_FLOOR, level, randomState);
            if (target != GeoTile.NO_DATA && weight > 0.0) {
                expected = (int) Math.round(vanilla + (target - vanilla) * weight);
            }
        }

        LOGGER.info("GEOWORLD-SURVEY x={} z={} topY={} ground={} top={} waterInTop24={} target={} w={} vanilla={} expected={} blocks={}",
                x, z, topY, groundY, top.getBlock(), waterInTop24, target,
                String.format("%.2f", weight), vanilla, expected, topBlocks);
        return new ColumnReport(x, z, topY, groundY, top, waterInTop24, target, weight,
                vanilla, expected, topBlocks);
    }
}
